### ISSUE TITLE
Allow more option to be passed to piuparts

### ISSUE THREAD

**Issue by charles2910** [evgeni/action-piuparts#7]
Hi,thanks for publishing the action!

I'm giving it a go and I'd like to pass additional flags to piuparts. For instance, I'd like to test against bookworm, I have to set the base-image to `debian:bookworm` and also pass `-d bookworm` to piuparts so it correctly test things. Right now, I'm abusing the `base-image` option passing `debian:bookworm -d bookworm`.

I can work on this and submit a MR. I'm saying this because last commmit was 5 months ago and I don't know if you intend to maintain this action further. If you do, I will gladly work on it. If not, probably will fork and implement stuff.

Thanks anyway for paving the way!

**Comment by evgeni** [comment]
Absolutely, this sounds like a good addition. If you can provide a PR that'd be awesome.
